name: fairbid_flutter
description: Unofficial Flutter plugin for FairBid SDK - the advertisement mediation platform. Supports banner, interstitial and rewarded video ads.
version: 1.0.1
homepage: https://github.com/ukasz123/fairbid_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  
  meta: ^1.1.7

  rxdart: '>=0.26.0 <2.0.0'
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.11.5
  build_version: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: pl.ukaszapps.fairbid_flutter
        pluginClass: FairBidFlutterPlugin
      ios:
        pluginClass: FairbidFlutterPlugin
